name: CI/CD Pipeline with Kubernetes

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install & test (optional)
      - name: Install dependencies
        run: npm ci --prefix user-service

      - name: Run tests
        run: npm test --prefix user-service || echo "no tests found"

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      # 6️⃣ Set up kubectl
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # 7️⃣ Configure kubeconfig
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      # 8️⃣ Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/user-deployment

      # 9️⃣ Verify deployment
      - name: Verify running pods and services
        run: |
          kubectl get pods
          kubectl get services
